### PR TITLE
Fix org-starter recipe again

### PR DESCRIPTION
**Pull request by conao3**
My work log and that log tell us those recipes produce same effect.

```
 ~/d/f/melpa    hub pr checkout 6266                              1387ms  金  7/ 5 09:27:16 2019
Switched to branch 'org-starter-update'


 ~/d/f/melpa   org-starter-update  make recipes/org-starter       3935ms  金  7/ 5 22:43:35 2019
 • Building package org-starter ...
Package: org-starter
Fetcher: github
Source:  https://github.com/akirak/org-starter.git

Updating /Users/conao/dev/forks/melpa/working/org-starter/
Built org-starter in 3.091s, finished at Fri Jul  5 22:43:42 2019
 ✓ Success:
128 -rw-r--r--  1 conao  staff    61K  7  5 22:43 packages/org-starter-20190703.2159.el
  8 -rw-r--r--  1 conao  staff   371B  7  5 22:43 packages/org-starter-20190703.2159.entry
160 -rw-r--r--  1 conao  staff    78K  7  5 03:26 packages/org-starter-20190703.2159.tar
  8 -rw-r--r--  1 conao  staff   969B  7  5 22:43 packages/org-starter-badge.svg
  8 -rw-r--r--  1 conao  staff    68B  7  5 22:43 packages/org-starter-readme.txt



 ~/d/f/melpa   org-starter-update  git diff                                金  7/ 5 22:44:50 2019
diff --git a/recipes/org-starter b/recipes/org-starter
index b43293a8..ff4f91e6 100644
--- a/recipes/org-starter
+++ b/recipes/org-starter
@@ -1,8 +1,5 @@
-(org-starter :repo "akirak/org-starter"
-             :fetcher github
-             :files
-             ("org-starter.el" "org-starter-*.el"
-              "doc/dir" "doc/*.info" "doc/*.texi" "doc/*.texinfo"
-              (:exclude ".dir-locals.el" "test.el" "tests.el" "*-test.el" "*-tests.el"
-                        "org-starter-swiper.el"
-                        "org-starter-extras.el")))
+(org-starter
+ :repo "akirak/org-starter"
+ :fetcher github
+ :files (:defaults
+         (:exclude "org-starter-swiper.el" "org-starter-extras.el")))



 ~/d/f/melpa   org-starter-update *  make recipes/org-starter              金  7/ 5 22:46:18 2019
 • Building package org-starter ...
Package: org-starter
Fetcher: github
Source:  https://github.com/akirak/org-starter.git

Updating /Users/conao/dev/forks/melpa/working/org-starter/
Copying files (->) and directories (=>)
  from /Users/conao/dev/forks/melpa/working/org-starter/
  to /var/folders/02/ynsv5hcs3cqdn1rff7l5t9680000gn/T/org-starterjqbcOQ/org-starter-20190703.2159
    counsel-org-starter.el -> counsel-org-starter.el
    helm-org-starter.el -> helm-org-starter.el
    org-starter.el -> org-starter.el
Built org-starter in 2.670s, finished at Fri Jul  5 22:46:25 2019
 ✓ Success:
128 -rw-r--r--  1 conao  staff    61K  7  5 22:43 packages/org-starter-20190703.2159.el
  8 -rw-r--r--  1 conao  staff   368B  7  5 22:46 packages/org-starter-20190703.2159.entry
160 -rw-r--r--  1 conao  staff    78K  7  5 22:46 packages/org-starter-20190703.2159.tar
  8 -rw-r--r--  1 conao  staff   969B  7  5 22:46 packages/org-starter-badge.svg
  8 -rw-r--r--  1 conao  staff    68B  7  5 22:46 packages/org-starter-readme.txt
```

### CODE REVIEW

**Comment by akirak** [comment]
Thanks, but is it safe to include `counsel-org-starter.el` and `helm-org-starter-el`? They depend on extra packages like ivy and helm, which, as far as I remember, will break the package. That's why I specified `org-starter.el` and `org-starter-*.el` rather than `*.el`.

**Comment by akirak** [comment]
BTW, I like the way you manage Git repositories.

> /Users/conao/dev/forks/melpa/working/org-starter/

This structure looks neat. Is there a tool for maintaining a hierarchy like this, or did you create it manually?

**Comment by conao3** [comment]
Why don't you modify the recipe before adding the file? Or, if you make MELPA recognize different packages, it's a good idea to just separate the repositories.

**Comment by conao3** [comment]
The issue of the structure is out of topic, but it is maintained by https://github.com/conao3/dev

**Comment by akirak** [comment]
> Why don't you modify the recipe before adding the file? Or, if you make MELPA recognize different packages, it's a good idea to just separate the repositories.

Because they are relevant packages, and I can test them together before org-starter.el is available on MELPA. Even [swiper](https://github.com/abo-abo/swiper) is doing so, so I don't think it is a bad idea.

**Comment by akirak** [comment]
> The issue of the structure is out of topic, but it is maintained by https://github.com/conao3/dev

Thank you. I will take a look at it.

**Comment by conao3** [comment]
I don't tell you some different packages in the same repository is **bad idea**.
> Why don't you modify the recipe before adding the file? Or, if you make MELPA recognize different packages, it's a **good idea** to just separate the repositories.

I recommend you modify recipe before adding files as different packages.
How many packages are you adding to this repository? Common sense suggests that there are no more than 5~10, and the effort to modify the recipe is much less than adding the package.

**Comment by akirak** [comment]
> I recommend you modify recipe before adding files as different packages.

Sorry, I focused only on the latter sentence in the quote. I have never seen a person who updates his/her recipe before he updates his package, while I saw several cases where an updated recipe was sent after it was broken. People are lazy by default.

> How many packages are you adding to this repository? Common sense suggests that there are no more than 5~10, and the effort to modify the recipe is much less than adding the package.

There probaby won't be more than five. Actually, `helm-org-starter` and `counsel-org-starter` are out of date now. I don't think I need to publish them to MELPA, but `org-starter-swiper` would be slighty more useful.

Your updated recipe seems to be wrong. Your recipe generates a tar file, while mine a single elisp file. Maybe you should run `make clean` before rebuilding a package.

**Comment by conao3** [comment]
Thanks for your point. I update the recipe.
 I ref `use-package` and `use-package-chords` recipe.

https://github.com/melpa/melpa/blob/master/recipes/use-package
```
(use-package
    :fetcher github
    :repo "jwiegley/use-package"
    :files (:defaults (:exclude "bind-key.el"
                                "bind-chord.el"
                                "use-package-chords.el"
                                "use-package-ensure-system-package.el")))
```

https://github.com/melpa/melpa/blob/master/recipes/use-package-chords
```
(use-package-chords :repo "jwiegley/use-package"
                    :fetcher github
                    :files ("use-package-chords.el"))
```

So the strategy of main package specific files with `:defaults` and child package specific the file only is fit your situation.

**Comment by conao3** [comment]
But it is you to maintain recipes and packages. So it depends on you.
I thought I was too interference you, sorry.

**Comment by conao3** [comment]
Reverse reference: https://github.com/melpa/melpa/pull/6266

**Pull request closed without merging**
